Só insere uma vez no banco
CO
2022-11-03 17:20:39.090  WARN 7396 --- [nio-8081-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 02000
2022-11-03 17:20:39.091 ERROR 7396 --- [nio-8081-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : Nenhum resultado foi retornado pela consulta.
2022-11-03 17:20:39.113 ERROR 7396 --- [nio-8081-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: could not extract ResultSet; nested exception is org.hibernate.exception.GenericJDBCException: could not extract ResultSet] with root cause

org.postgresql.util.PSQLException: Nenhum resultado foi retornado pela consulta.